export interface Venue {
  name: string;
  lat: number;
  lng: number;
  sports: string[];
  address: string;
  url: string;
}

export const GLASGOW_MAP_CENTER: [number, number] = [-4.2518, 55.8642];

export const DISCOVER_VENUES: Venue[] = [
  {
    name: "Glasgow Club Emirates Arena",
    lat: 55.8515,
    lng: -4.2284,
    sports: ["Athletics", "Basketball", "Badminton", "Swimming", "Gym"],
    address: "1000 London Rd, Glasgow G40 3HG",
    url: "https://glasgowclub.org/venues/emirates-arena/",
  },
  {
    name: "Glasgow Club Kelvin Hall",
    lat: 55.8676,
    lng: -4.2977,
    sports: ["Gym", "Athletics", "Climbing", "Basketball"],
    address: "1445 Argyle St, Glasgow G3 8AW",
    url: "https://glasgowclub.org/venues/kelvin-hall/",
  },
  {
    name: "Glasgow Club Scotstoun",
    lat: 55.877,
    lng: -4.3538,
    sports: ["Badminton", "Squash", "Gym", "Padel", "Swimming"],
    address: "Danes Dr, Glasgow G14 9HD",
    url: "https://glasgowclub.org/venues/scotstoun/",
  },
  {
    name: "Glasgow Club Tollcross",
    lat: 55.8456,
    lng: -4.1773,
    sports: ["Swimming", "Gym", "Basketball", "Badminton"],
    address: "350 Wellshot Rd, Glasgow G32 7QR",
    url: "https://glasgowclub.org/venues/tollcross/",
  },
  {
    name: "Glasgow Club Gorbals",
    lat: 55.8467,
    lng: -4.2582,
    sports: ["Gym", "Swimming", "Badminton"],
    address: "160 Ballater St, Glasgow G5 0QH",
    url: "https://glasgowclub.org/venues/gorbals/",
  },
  {
    name: "Glasgow Club Maryhill",
    lat: 55.8934,
    lng: -4.2857,
    sports: ["Gym", "Basketball", "Badminton"],
    address: "45 Shawpark St, Glasgow G20 9DR",
    url: "https://glasgowclub.org/venues/maryhill/",
  },
  {
    name: "Glasgow Club Pollok",
    lat: 55.8189,
    lng: -4.3201,
    sports: ["Gym", "Swimming", "Tennis"],
    address: "27 Cowglen Rd, Glasgow G53 6EW",
    url: "https://glasgowclub.org/venues/pollok/",
  },
  {
    name: "Glasgow Club Springburn",
    lat: 55.887,
    lng: -4.2271,
    sports: ["Gym", "Badminton", "Basketball"],
    address: "Springburn Rd, Glasgow G21 1GH",
    url: "https://glasgowclub.org/venues/springburn/",
  },
  {
    name: "Glasgow Club North Woodside",
    lat: 55.8751,
    lng: -4.2724,
    sports: ["Swimming", "Gym"],
    address: "Braid Sq, Glasgow G4 9YB",
    url: "https://glasgowclub.org/venues/north-woodside/",
  },
  {
    name: "Glasgow Club Milton",
    lat: 55.9079,
    lng: -4.2643,
    sports: ["Gym", "Badminton", "Basketball"],
    address: "Liddesdale Rd, Glasgow G22 6RB",
    url: "https://glasgowclub.org/venues/milton/",
  },
  {
    name: "Glasgow Club Palace of Art",
    lat: 55.8397,
    lng: -4.3102,
    sports: ["Gym", "Gymnastics"],
    address: "Bellahouston Park, Glasgow G41 5BW",
    url: "https://glasgowclub.org/venues/palace-of-art/",
  },
  {
    name: "Toryglen Regional Football Centre",
    lat: 55.8228,
    lng: -4.2356,
    sports: ["Football"],
    address: "Prospecthill Circus, Glasgow G42 0LJ",
    url: "https://glasgowclub.org/venues/toryglen/",
  },
  {
    name: "Powerleague Glasgow Townhead",
    lat: 55.8644,
    lng: -4.238,
    sports: ["Football"],
    address: "McPhater St, Glasgow G4 0HW",
    url: "https://www.powerleague.com/location/glasgow",
  },
  {
    name: "Powerleague Paisley",
    lat: 55.8448,
    lng: -4.4201,
    sports: ["Football"],
    address: "Underwood Rd, Paisley PA3 1TJ",
    url: "https://www.powerleague.com/location/paisley",
  },
  {
    name: "Goals Glasgow West",
    lat: 55.9011,
    lng: -4.3612,
    sports: ["Football"],
    address: "2680 Great Western Rd, Glasgow G15 6SA",
    url: "https://www.goalsfootball.co.uk/our-clubs/scotland/glasgow-west",
  },
  {
    name: "Goals Glasgow South",
    lat: 55.805,
    lng: -4.278,
    sports: ["Football"],
    address: "Scotland St, Glasgow G5 8NL",
    url: "https://www.goalsfootball.co.uk/our-clubs/scotland/glasgow-south",
  },
  {
    name: "Scotland Street Indoor Pitches",
    lat: 55.848,
    lng: -4.269,
    sports: ["Football"],
    address: "Scotland St, Glasgow G5",
    url: "https://www.goalsfootball.co.uk",
  },
  {
    name: "The Lagoon Leisure Centre",
    lat: 55.8448,
    lng: -4.4231,
    sports: ["Swimming", "Gym", "Badminton", "Basketball"],
    address: "Christie St, Paisley PA1 1NB",
    url: "https://www.oneren.org/venues/leisure-venues/lagoon-leisure-centre/",
  },
  {
    name: "ON-X Linwood",
    lat: 55.8369,
    lng: -4.4839,
    sports: ["Football", "Athletics", "Badminton", "Basketball", "Gym"],
    address: "Napier St, Linwood PA3 3DE",
    url: "https://www.oneren.org/venues/leisure-venues/on-x/",
  },
  {
    name: "Ralston Community Sports Centre",
    lat: 55.8397,
    lng: -4.3921,
    sports: ["Football", "Tennis"],
    address: "Ralston Ave, Paisley PA1 3AX",
    url: "https://www.oneren.org/venues/leisure-venues/ralston-community-sports-centre/",
  },
  {
    name: "Renfrew Leisure Centre",
    lat: 55.8763,
    lng: -4.3891,
    sports: ["Swimming", "Gym", "Badminton"],
    address: "Inchinnan Rd, Renfrew PA4 8ND",
    url: "https://www.oneren.org/venues/leisure-venues/renfrew-leisure-centre/",
  },
  {
    name: "University of Glasgow Sport",
    lat: 55.8721,
    lng: -4.2893,
    sports: ["Tennis", "Squash", "Gym", "Basketball", "Badminton", "Swimming"],
    address: "Stevenson Building, Glasgow G12 8QQ",
    url: "https://www.gla.ac.uk/myglasgow/sport/",
  },
  {
    name: "University of Strathclyde Sport",
    lat: 55.8617,
    lng: -4.2433,
    sports: ["Gym", "Badminton", "Basketball", "Swimming"],
    address: "Rottenrow, Glasgow G4 0NG",
    url: "https://www.strath.ac.uk/sport/",
  },
  {
    name: "University of the West of Scotland Sport (Paisley)",
    lat: 55.8483,
    lng: -4.4287,
    sports: ["Gym", "Football", "Basketball"],
    address: "High St, Paisley PA1 2BE",
    url: "https://www.uws.ac.uk/sport/",
  },
  {
    name: "Playsport Arena East Kilbride",
    lat: 55.7817,
    lng: -4.1749,
    sports: ["Basketball", "Gym"],
    address: "The Murray, East Kilbride G75 0YA",
    url: "https://playsportarena.com",
  },
  {
    name: "National Tennis Centre Scotstoun",
    lat: 55.877,
    lng: -4.3538,
    sports: ["Tennis"],
    address: "Danes Dr, Glasgow G14 9HD",
    url: "https://www.lta.org.uk",
  },
  {
    name: "Glasgow Green Tennis Courts",
    lat: 55.8503,
    lng: -4.2347,
    sports: ["Tennis"],
    address: "Glasgow Green, Glasgow G40 1AT",
    url: "https://www.glasgowlife.org.uk",
  },
  {
    name: "Victoria Park Tennis Courts",
    lat: 55.8861,
    lng: -4.3392,
    sports: ["Tennis"],
    address: "Victoria Park Dr S, Glasgow G14 9NZ",
    url: "https://www.glasgowlife.org.uk",
  },
  {
    name: "Glasgow Green Parkrun",
    lat: 55.8503,
    lng: -4.2301,
    sports: ["Running"],
    address: "Glasgow Green, Glasgow G40",
    url: "https://www.parkrun.org.uk/glasgowgreen/",
  },
  {
    name: "Pollok Park Parkrun",
    lat: 55.8136,
    lng: -4.3274,
    sports: ["Running"],
    address: "Pollok Country Park, Glasgow G43 1AT",
    url: "https://www.parkrun.org.uk/pollok/",
  },
  {
    name: "Kelvingrove Park Running Track",
    lat: 55.8686,
    lng: -4.2842,
    sports: ["Running"],
    address: "Kelvingrove Park, Glasgow G3 7TA",
    url: "https://www.glasgowlife.org.uk",
  },
  {
    name: "Sir Chris Hoy Velodrome",
    lat: 55.8522,
    lng: -4.2268,
    sports: ["Cycling"],
    address: "London Rd, Glasgow G40 3HG",
    url: "https://www.glasgowlife.org.uk/sport/venues/sir-chris-hoy-velodrome",
  },
  {
    name: "Scotstoun Squash Centre",
    lat: 55.877,
    lng: -4.3538,
    sports: ["Squash"],
    address: "Danes Dr, Glasgow G14 9HD",
    url: "https://glasgowclub.org/venues/scotstoun/",
  },
  {
    name: "Renfrew Victory Baths",
    lat: 55.8763,
    lng: -4.3901,
    sports: ["Swimming"],
    address: "Inchinnan Rd, Renfrew PA4",
    url: "https://www.oneren.org",
  },
  {
    name: "Ayr Leisure Centre",
    lat: 55.4654,
    lng: -4.629,
    sports: ["Swimming", "Gym", "Badminton"],
    address: "Citadel Leisure Centre, South Harbour St, Ayr KA7 1NU",
    url: "https://www.south-ayrshire.gov.uk/sports-leisure",
  },
  {
    name: "Dam Park Stadium Ayr",
    lat: 55.4742,
    lng: -4.6198,
    sports: ["Athletics", "Football"],
    address: "Dam Park, Ayr KA8 0DZ",
    url: "https://www.south-ayrshire.gov.uk",
  },
];
